### ISSUE TITLE
page is stuck on 'please wait while..'

### ISSUE THREAD

**Issue by MCswan4u** [diane-villemure/moodle_payment_plugin#1]
This plugin is exactly what I'm looking for, the discount part, but after several attempts, I'm just not able to move past the 'please wait while...' page. The automatic registration after payment doesn't seem to work. The paypal payments works. When I refresh or log out and back in, I'm not registered into any course. Any advise would be greatly appreciated. I have also updated the API link on paypal and disabled it as well - result is the same.

**Comment by diane-villemure** [comment]
That plugin doesn't work. Go to the fixed version here: https://bitbucket.org/lmsdoctor/moodle-enrol_payment/downloads/

**Comment by MCswan4u** [comment]
THANK YOU so much! I downloaded and tested it and now I at least get enrolled. The only issue is a missing parameter (get_payment_from_toke) any idea where to set/get the token information? 
![error](https://user-images.githubusercontent.com/19592057/135578101-7997b6e2-cdc1-4e62-b138-fb13a012adfc.jpg)

**Comment by diane-villemure** [comment]
This issue has been fixed but I guess it hasn't be committed to the master. See [https://bitbucket.org/lmsdoctor/moodle-enrol_payment/commits/9219998142774b69a96a6194b885344e00776e54?at=fix-privacy]

**Comment by MCswan4u** [comment]
Hi Diane,

Thank you again for your help. I updated the files, but unfortunately, I
still get the same error message.Will see if I can somehow figure this out.

Thanks again.

*Kind regards,*
